[customizations.fdo]
manufacturing_server_url = ""
diun_pub_key_insecure = "true"

[customizations.installer.kickstart]
contents = """
text --non-interactive
zerombr
clearpart --all --initlabel --disklabel=gpt
autopart --noswap --type=lvm


# user setup
user --name redhat --password password --plaintext --groups wheel

# network configuration
network --bootproto=dhcp --device=link --activate --onboot=on
poweroff

%post --log=/var/log/anaconda/post-install.log --erroronfail
export MANUFACTURING_SERVER_URL="http://manufacturing.sandbox2938.opentlc.com"
export DIUN_PUB_KEY_INSECURE="true"

# For DNS resolution
echo "nameserver 192.168.1.1" > /etc/resolv.conf

/usr/libexec/fdo/fdo-manufacturing-client
%end
"""