FROM registry.redhat.io/rhel9/rhel-bootc:9.5

ADD etc etc

RUN dnf install -y flightctl-agent && \
    systemctl enable flightctl-agent.service

RUN rm -rf /opt && \
    mkdir -p /opt/crio

## Embedding flightctl configuration and certificates into image
ADD ../../certs/config.yaml /etc/flightctl/
ADD ../../certs/ca.crt /etc/flightctl/certs/
ADD ../../certs/client-enrollment.* /etc/flightctl/certs/